title: ESPHome-Configs.io
description: >- # this means to ignore newlines until "baseurl:"
  A database of configuration files and guides for devices commonly flashed with https://esphome.io firmware.
url: "https://esphome-configs.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - docker-compose.yml
  - README.md

collections:
  devices:
    output: true
    permalink: /devices/:path/

defaults:
  -
    scope:
      path: "_devices"
    values:
      layout: "device"

# Theme Settings

# Logo
logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true


# Heading Anchor Links
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "ESPHome-Configs.io on GitHub":
    - "//github.com/jonathanadams/esphome-configs"